version: '3'

services:
  mysql_server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
      MYSQL_DATABASE: ContaCerta
    ports:
      - "3308:3306"
    expose:
      - 3308
    volumes:
      - ./volumes/MySql:/var/lib/mysql
    networks:
      - poc_contaCerta

  backend:
    container_name: 'backend-api'
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: bash -c "npm install && npm start"
    volumes:
      - ./../backend/:/usr/app
    ports:
      - "3010:3011"
    networks:
      - poc_contaCerta

networks:
  poc_contaCerta:
    driver: bridge