version: '3'

services:
  mysql_server:
    container_name: 'bd-mysql'
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure:5
    env_file:
      - ./conf/db.env
    ports:
      - "3306:3306"
    expose:
      - 3308
    volumes:
      - ./volumes/db/MySql/data:/var/lib/mysql:rw
      - ./volumes/db/MySql/conf/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./volumes/db/MySql/Scripts/up:/docker-entrypoint-initdb.d
    networks:
      - poc_contaCerta

  backend:
    container_name: 'backend-api'
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - mysql_server
    command: bash -c "npm install && npm start"
    volumes:
      - ./../backend/:/usr/app
    ports:
      - "3010:3005"
    networks:
      - poc_contaCerta

networks:
  poc_contaCerta:
    driver: bridge